name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
          
      - name: Snyk auth
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: 0a4366c1-d6bc-467a-b1b5-bae574f6d8cc
        with:
          command: auth 
          
      - name: Snyk test
        uses: snyk/actions@0.3.0
        with:
          command: test 
          

