name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
          
      - name: Snyk auth
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: 3f1a12a9-3b79-413a-8e9c-ceb0f8949176
        with:
          command: snyk auth 
          
      - name: Snyk test
        uses: snyk/actions@0.3.0
        with:
          command: test 
          

