name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: npm install
        run:  npm install
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: snyk install
        run:  npm install snyk
            
      - name: install snyk to html
        run:  npm install snyk-to-html -g
        
      - name: print to html
        run:  npm install snyk
              snyk test --json | snyk-to-html -o result.html
        
        
  

        


          
          

