name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
          
      - name: Snyk
        uses: snyk/actions@0.3.0
        with:
          command: test
