name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: npm install
        run:  npm install
        
      - name: snyk install
        run:  npm install snyk
        
      - name: snyk auth
        run:  snyk auth 
        
      - name: install snyk to html
        run:  npm install snyk-to-html -g
        
      - name: run snyk test
        run:  snyk test --json | snyk-to-html -o result.html
  

        


          
          

